name: RVVM X86_64 Release Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: release
  USE_RV64: 1
  USE_JIT: 1
  USE_FPU: 1
  USE_PCI: 1
  USE_FB: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile release
      run: make -j$(nproc)
    - name: Pack artifact into tar
      run: tar -cvf rvvm_x86_64.tar release.linux.x86_64/rvvm_x86_64
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: rvvm-x86_64
        path: rvvm_x86_64.tar

