name: RVVM X86_64 Release Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: release
  USE_RV64: 1
  USE_JIT: 1
  USE_FPU: 1
  USE_PCI: 1
  USE_FB: 1

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile release
        run: make -j$(nproc)
      - name: Pack artifact into zip
        run: zip rvvm_x86_64.zip release.darwin.x86_64/rvvm_x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rvvm-darwin-x86_64
          path: rvvm_x86_64.zip

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile release
      run: make -j$(nproc)
    - name: Pack artifact into zip
      run: zip rvvm_x86_64.zip release.linux.x86_64/rvvm_x86_64
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: rvvm-linux-x86_64
        path: rvvm_x86_64.zip

